stages:
  - test
  - build

before_script:
  - chmod +x ./docker_install.sh > /dev/null
  - mkdir -p /go/src/gitlab.com/nidadinch /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/nidadinch/to-do-app-backend
  - ln -s /go/src/gitlab.com/nidadinch /go/src/_/builds/nidadinch
  - make dep

test:
  stage: test
  image: golang:1.10-alpine3.7
  script:
    - make test

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:latest"
