apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
  labels:
    app: backend
spec:
  defaultBackend:
    service:
      name: backend-entrypoint
      port:
        number: 80
