kind: Service
apiVersion: v1
metadata:
  name: backend-entrypoint
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
